### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ACoday** [SeattleGiveCamp/SGC2017_FEN#18]
Somali and Amharic are listed as the 4th most spoken languages in King County.   Somali also has a large concentration of families in poverty.  

Also interesting, Somali is the #2 bilingual language in the Seattle School District.

I received feedback that Bing is the better translator. Is there a way to have dual translation?  Or should we go with Google translator?

•	Bing -  Spanish, Vietnamese, Chinese, Arabic, Korean, Russian, Filipino and French
•	Google - Somali and Amharic 

Alice Coday
206.251.7705

**Comment by devinyr** [comment]
Would be nice to have all of these
አማርኛ - Amharic
العربية - Arabic
អក្សរខ្មែរ - Cambodian (Khmer)
中文 - Chinese (simplified)
الفارسية - Farsi
Français - French
Deutsche - German
हिंदी - Hindi
日本語 - Japanese
한국어 - Korean
ພາສາລາວ - Lao
Oromiffaa - Oromo
ਪੰਜਾਬੀ - Punjabi
Română - Romanian
Русский - Russian
Af-soomaali - Somali
Español - Spanish
Tagalog - Tagalog
Українська - Ukranian
Tiếng Việt - Vietnamese

**Comment by jamesmontemagno** [comment]
Added in best of my ability
