### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by ACoday** [SeattleGiveCamp/SGC2017_FEN#23]
- [x] Navigate To (Some are correct and some still show NavigateTo).
1.	Korean - not translating
2.	Lao – not translating
3.	Vietnamese – not translating
4.	Punjabi – not translating
5.	Lao – not translating
6.	Korean – not translating
7.	Filipino – not translating
8.	Chinese (traditional) – not translating
9.	Chinese (simple) – not translating
10.	Amharic – not translating

- [x] Learn more is not translating in Khmer or Somali

- [x] Banking Topic Area
1.	Label – Repayment of Outstanding Overdraft Required Before Opening is not translating in all languages.
2.	French – yes & no responses are in English instead of oui & pas
3.	German - yes & no responses are in English instead of ja & nein
4.	Labels are in English for Amharic, Filipino, Lao, Punjabi, Khmer and Somali
5.	Somali, Khmer both labels and data are in English.

- [x] Tax Prep Topic Area 
1.    The description is not translating in Amharic
2.	Somali, Khmer both labels and data are in English.
3.	Lao – Labels for Name and Street Address are not translating/Data description is not translating  
4.	Punjabi - Data description is not translating                                                                 
                                                                                                                   
- [x] Financial Education and Counseling 
1.	The description is not translating in Amharic
2.	Somali, Khmer both labels and data are in English.
3.	Lao – Labels for Name and Street Address are not translating/Data description is not translating                                                                        
4.	Punjabi - Data description is not translating  

- [x] Community Resources
1.	The description is not translating in Amharic
2.	Somali, Khmer both labels and data are in English.
3.	Lao – Labels for Name and Street Address are not translating/Data description is not translating                                                                        
4.	Punjabi - Data description is not translating  

- [x] Legal
1.	The description is not translating in Amharic
2.	Somali, Khmer both labels and data are in English.
3.	Lao – Labels for Name and Street Address are not translating/Data description is not translating                                                                        
4.	Punjabi - Data description is not translating  

- [x] Transportation
1.	The description is not translating in Amharic
2.	Somali, Khmer both labels and data are in English.
3.	Lao – Labels for Name and Street Address are not translating/Data description is not translating                                                                        
4.	Punjabi - Data description is not translating  

- [x] Health
1.	The description is not translating in Amharic
2.	Somali, Khmer both labels and data are in English.
3.	Lao – Labels for Name and Street Address are not translating/Data description is not translating                                                                        
4.	Punjabi - Data description is not translating  

- [x] Food
1.	The description is not translating in Amharic
2.	Somali, Khmer both labels and data are in English.
3.	Lao – Labels for Name and Street Address are not translating/Data description is not translating                                                                        
4.	Punjabi - Data description is not translating  

- [x] Services shows in the prior language selected.
Example Korean was previously selected, and I changed the language to Spanish, but Services still shows in Korean.

**Comment by jamesmontemagno** [comment]
I have gone through and updated all of the missing translations and some of the changes requested when changing languages.

One things that is not support will be translating some of the resource descriptions to Somali on the fly. This is because the translation service does not support it. Any of the hard coded ones in the app I was able to add manually though.

Should have a new releases soon.

Please open up a new issue with anything new that you find.
