### ISSUE TITLE
Language Issues

### ISSUE THREAD

**Issue by ACoday** [SeattleGiveCamp/SGC2017_FEN#24]
- [ ] Content Topic (8) Page not translating in:  Amharic, Khmer, Lao, Punjabi, Somali      

Navigate To (Shows NavigateTo).

- [x] Vietnamese – not translating
- [x] Arabic – not translating

Banking Topic Area

- [ ] Data under Label “Repayment of Outstanding Overdraft Required Before Opening” is not translating in all languages.
- [x] Labels – “minimum opening deposit”, “overdraft fees” & “online bill” pay are not translating in Lao
- [x] Label “overdraft fees” is not translating in Amharic
- [x] Label “online bill pay” and “secured credit card” are not translating in Filipino
- [x] Label “online bill pay” is not translating in Romanian

Tax Prep Topic Area 

- [ ] Label “Description” data is not translating in Amharic, Khmer, Lao, Punjabi, Somali      
- [x] Label “City” is not translating in Khmer and Ukrainian.     
- [x] Ukranian s/b Ukrainian  (there are two “i”)
- [x] Label “Name” is not translating in Hindi or German. 

Financial Education and Counseling 

- [ ] Label “Description” data is not translating in Amharic, Khmer, Lao, Punjabi, Somali
- [x] Label “City” is not translating in Khmer and Ukrainian.
- [x] Ukranian s/b Ukrainian  (there are two “i”)
- [x] Label “Name” is not translating in Hindi or German.

Community Resources

- [ ] Label “Description” data is not translating in Amharic, Khmer, Lao, Punjabi, Somali
- [x] Label “City” is not translating in Khmer and Ukrainian.
- [x] Ukranian s/b Ukrainian  (there are two “i”)
- [x] Label “Name” is not translating in Hindi or German.

Legal

- [ ] Label “Description” data is not translating in Amharic, Khmer, Lao, Punjabi, Somali
- [x] Label “City” is not translating in Khmer and Ukrainian.
- [x] Ukranian s/b Ukrainian  (there are two “i”)
- [x] Label “Name” is not translating in Hindi or German.

Transportation

- [ ] The “Description” data is not translating in Amharic, Khmer, Lao, Punjabi, Somali
- [x] Label “City” is not translating in Khmer and Ukrainian.
- [x] Ukranian s/b Ukrainian  (there are two “i”)
- [x] Label “Name” is not translating in Hindi or German.

Health

- [ ] Label “Description” data is not translating in Amharic, Khmer, Lao, Punjabi, Somali
- [x] Label “City” is not translating in Khmer and Ukrainian. 
- [x] Ukranian s/b Ukrainian  (there are two “i”)
- [x] Label “Name” is not translating in Hindi or German.

Food

- [ ]  Label  “Description” data is not translating in Amharic, Khmer, Lao, Punjabi, Somali
- [x] 	Label “City” is not translating in Khmer and Ukrainian.
- [x] 	Ukranian s/b Ukrainian  (there are two “I”)
- [x] 	Label “Name” is not translating in Hindi or German.

- [x] Services shows in the prior language selected. Example Korean was previously selected, and I changed the language to Spanish, but Services still shows in Korean.

**Comment by jamesmontemagno** [comment]
Name is Name in german

**Comment by jamesmontemagno** [comment]
For the labels, unfortunatelly we can only translate ones that are supported:
https://msdn.microsoft.com/en-us/library/hh456380.aspx

So, Amharic, Khmer, Lao, Punjabi, Somali are not supported and can not be translated on the fly :(

I have finished the rest of the missing translations to the best of our ability.
