### ISSUE TITLE
Admin portal has no security

### ISSUE THREAD

**Issue by plitwin** [SeattleGiveCamp/SGC2017_FEN#9]
Need to add security and re-deploy the portal

**Comment by jamesmontemagno** [comment]
I think we fixed this? @plitwin

**Comment by ACoday** [comment]
James,

I found a few more translation issues (attached).  Github is not allowing me to submit a new issue.


Alice Coday
Financial Empowerment Network
acoday@everyoneiswelcome.org<mailto:acoday@everyoneiswelcome.org> ● 206.251.7705<mailto:jmeissner@skcabc.org>
www.everyoneiswelcome.org<http://www.everyoneiswelcome.org/>
My regular office hours are Monday, Wednesday  and  Thursday from 10:30 am – 3:30 pm

Celebrating 11 Years!  Change Counts!™

**Comment by ACoday** [comment]
James,

I just made the entry in github.


Alice Coday
Financial Empowerment Network
acoday@everyoneiswelcome.org<mailto:acoday@everyoneiswelcome.org> ● 206.251.7705<mailto:jmeissner@skcabc.org>
www.everyoneiswelcome.org<http://www.everyoneiswelcome.org/>
My regular office hours are Monday, Wednesday  and  Thursday from 10:30 am – 3:30 pm

Celebrating 11 Years!  Change Counts!™




From: Alice Coday
Sent: Sunday, December 17, 2017 3:34 PM
To: 'SeattleGiveCamp/SGC2017_FEN' <reply@reply.github.com>; SeattleGiveCamp/SGC2017_FEN <SGC2017_FEN@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [SeattleGiveCamp/SGC2017_FEN] Admin portal has no security (#9)

James,

I found a few more translation issues (attached).  Github is not allowing me to submit a new issue.


Alice Coday
Financial Empowerment Network
acoday@everyoneiswelcome.org<mailto:acoday@everyoneiswelcome.org> ● 206.251.7705<mailto:jmeissner@skcabc.org>
www.everyoneiswelcome.org<http://www.everyoneiswelcome.org/>
My regular office hours are Monday, Wednesday  and  Thursday from 10:30 am – 3:30 pm

Celebrating 11 Years!  Change Counts!™
